### ISSUE TITLE
Error when trying to preview file

### ISSUE THREAD

**Issue by vanem** [kaishuu0123/graphviz-dot.js#2]
Using vs code:

Version 1.22.1
Commit 950b8b0d37a9b7061b6f0d291837ccc4015f5ecd
Date 2018-04-06T02:26:57.615Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Installed the plugin, configured dot path.

When I try to preview a dot file i get this error:
Unable to open 'Preview 'Untitled-1.txt'': An unknown error occurred. Please consult the log for more details..

**Comment by kaishuu0123** [comment]
Why did you close the issue?
Please tell me the cause.
